builds:
  - main: ./src/nr-spark-metric.go
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: distributions/linux/etc/nri-spark-metric/nr-spark-metric
archives:
  - wrap_in_directory: false
    files:
      - distributions/linux/*
